[project]
name = "mcp_example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
